on:
  push:
     paths:
       - 'home/scripts/**'
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: |
          chmod +x ./.github/scripts/create_scripts_docs.sh
          ./.github/scripts/create_scripts_docs.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update SCRIPTS.md (auto)" && git push
          exit 0
