on:
  push:
     paths:
       - '.github/assets/README_template.md'
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
      - name: Install required dependencies
        run: |
          go install github.com/anotherhadi/markdown-table-of-contents@latest
      - name: Run a script
        run: |
          chmod +x ./.github/scripts/create_readme.sh
          ./.github/scripts/create_readme.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update README.md (auto)" && git push
          exit 0
